print("=" * 60)
print("CONFIGURAR CORS EN AZURE PORTAL")
print("=" * 60)
print("")
print("PASOS:")
print("1. Ve al Portal de Azure: https://portal.azure.com")
print("2. Navega a: Storage Accounts > edubotstore2026")
print("3. En el menú lateral: Settings > Resource sharing (CORS)")
print("")
print("REGLAS PARA BLOB SERVICE:")
print("-" * 40)
print("| Campo               | Valor                    |")
print("| Allowed origins    | *                        |")
print("| Allowed methods   | GET, PUT, POST, DELETE   |")
print("| Allowed headers   | *                        |")
print("| Exposed headers   | Content-Type             |")
print("| Max age (seconds) | 3600                     |")
print("")
print("REGLAS PARA QUEUE SERVICE:")
print("-" * 40)
print("| Campo               | Valor                    |")
print("| Allowed origins    | *                        |")
print("| Allowed methods   | GET, POST                 |")
print("| Allowed headers   | *                        |")
print("| Exposed headers   | *                        |")
print("| Max age (seconds) | 3600                     |")
print("")
print("NOTA: Usa * para desarrollo, especifica tu dominio en producción")
print("")
print("RECURSOS:")
print("- Blob: https://edubotstore2026.blob.core.windows.net/")
print("- Queue: https://edubotstore2026.queue.core.windows.net/")
print("=" * 60)
